name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        
      - name: Prepare Package
        run: |
          yarn
          yarn prepare
        
      - name: Publish Package
        run: yarn release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}