name: Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Setup Identity
        run: |
          git config --global user.name VinayakNivalkar
          git config --global user.email vinayaknivalkar2002@gmail.com
      
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
        
      - name: Prepare Package
        run: |
          npm install
          npm run prepare
        
      - name: Publish Package
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
